spring:
    application:
        name: Carros Prod
    jpa:
        show-sql: true
    main:
        lazy-initialization: false
    
app:
    config:
        variavel: X
        valor1: 500
    montadora:
        motor-padrao: 130
